version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: sm1m4$b1s1n355!
      MYSQL_DATABASE: smimabd_business
      MYSQL_USER: smima_master
      MYSQL_PASSWORD: sm1m4$b1s1n355!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
